ALTER TABLE organization
ADD COLUMN postal_code VARCHAR(30) NOT NULL,
ADD COLUMN neighborhood VARCHAR(70) NOT NULL,
ADD COLUMN street VARCHAR(70) NOT NULL,
ADD COLUMN state CHAR(2) NOT NULL,
ADD COLUMN city VARCHAR(40) NOT NULL,
ADD COLUMN latitude NUMERIC NOT NULL,
ADD COLUMN longitude NUMERIC NOT NULL;